apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: lvm-image-registry-volume
  namespace: openshift-image-registry
  labels:
    type: local
spec:
  storageClassName: lvms-vg1
  resources:
    requests:
      storage: 40Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
